### ISSUE TITLE
Getting Continue to Work in GnG

### ISSUE THREAD

**Issue by cacophony1** [jotego/jt_gng#10]
Continue was working for me in the prior build of GnG, but with the latest I can't ever seem to continue. I've tried mapping different gamepad buttons, loading up coins initially, doing "start" followed by "fire", "coin" followed by "fire", "coin" followed by "start", switching off coin mode.... I can never get the continue to happen before the timer countdown reaches zero.

(this is using the MiSTer version)

edit: I just discovered that continue seems to work if I press fire and start **at the same time**. Was the original arcade like that too? Maybe it would be helpful to include that in the release notes?

**Comment by jotego** [comment]
Hi, CAPCOM followed that rule for early arcades. 1942 is the same. I will add it to the README file.
