### ISSUE TITLE
Missing jtframe

### ISSUE THREAD

**Issue by gyurco** [jotego/jt_gng#13]
This module is not in github, so the cores are unbuildable.

**Comment by jotego** [comment]
Here it is: https://github.com/jotego/jtframe
I still have to add documentation to jtframe and present it to the community, but I do not want to slow you down.
The idea is to have a common framework for MiST with a central repository, well documented and tested so everyone can benefit from it.

**Comment by gyurco** [comment]
Ah thanks, I thought it was just forgotten.
