### ISSUE TITLE
High score and player 1 & 2 text is cut off at the top

### ISSUE THREAD

**Issue by amoore2600** [jotego/jt_gng#14]
On this core the high score and player 1 & 2 text is cut off at the top when compared to MAME, see: https://imgur.com/a/lMyXtCB 

running with MiSTer.ini setting to confirm that my HDTV/HDMI is not being cut off due to the TV or TV's Bezel in attached MiSTer picture:
vscale_border=10        ; set vertical border for TVs cutting the upper/bottom parts of screen (1-99)

**Comment by jotego** [comment]
Hi,
This is fixed now and we'll be part of the next public release coming up in a few days. Source code will be updated then.
Thanks!

**Comment by amoore2600** [comment]
Awesome!
