### ISSUE TITLE
1Player Start - No permanent mapping

### ISSUE THREAD

**Issue by mickstone** [jotego/jt_gng#23]
MisTer Build - Commando

Is there any way to map a button to 1P Start?  F1 on the keyboard works, but I can't see any way to make this a permanent mapping to a joystick button.

Apologies if I'm just blind and can't see it,

**Comment by jotego** [comment]
I think you are using an old version. You can grab the latest one from here
<https://github.com/jotego/jtbin>. Note that there will be a new release
tomorrow.

**Comment by mickstone** [comment]
Was that the Commando core or the GnG core?

Great work btw, it blows me away how much effort you put into this and your depth of knowledge is amazing.
