### ISSUE TITLE
Some graphical glitches in Black Tiger

### ISSUE THREAD

**Issue by manast** [jotego/jt_gng#31]
From the fourth level I started to see some glitches, becomes worse in level 5, also when the glitches appear, the high score naming screen does not display properly the cursor from around the middle of the keys. Please see the attached screenshots:
Level 4:
![image](https://user-images.githubusercontent.com/95200/71530033-28c8e680-28e8-11ea-8374-e9a3df31ed62.png)
Level 5:
![image](https://user-images.githubusercontent.com/95200/71530046-31b9b800-28e8-11ea-94c3-311212524a33.png)
![image](https://user-images.githubusercontent.com/95200/71530066-3aaa8980-28e8-11ea-9bbd-a5daafb800c9.png)
Shop in level 5:
![image](https://user-images.githubusercontent.com/95200/71530071-439b5b00-28e8-11ea-804c-3b04e62b7317.png)
High score table (only appears broken after level 3 when the glitches appeared in the game):
![image](https://user-images.githubusercontent.com/95200/71530086-57df5800-28e8-11ea-868d-575eb3709be5.png)

Otherwise the game plays really well :). Trying to regain my skills to complete it with one credit.

**Comment by jotego** [comment]
I have fixed it now. It was a problem in the colour mixer. I'll upload the new binaries probably tomorrow. Thanks for reporting it :-)
