### ISSUE TITLE
Bionic Commando / Sprites corrupted 

### ISSUE THREAD

**Issue by shazz** [jotego/jt_gng#35]
Hi Jotego,

Whatever the rom version I am using, same issue, most of the sprites are corrupted (vertical lines).
Is it a SDRAM issue ? I'm using the "old" board (not the new SDRAM board for NeoGeo)

MiSTer version : MiSTer_20200101
Core: jtbiocom_20191201.rbf

Note: same issue with F1-Dream and Tiger Road

Thanks!

**Comment by jotego** [comment]
This is the same as this [issue](https://github.com/jotego/jtbin/issues/4). I am closing it here.
