### ISSUE TITLE
Double dragon sync issue with CRT on MiST

### ISSUE THREAD

**Issue by manast** [jotego/jt_gng#38]
Hello,

here a video that demonstrates the effect on my CRT. My CRT works well with NTSC signals (60Hz), and PAL (50Hz), so I think there should not be any problem with 57Hz either.
Would be interesting to know if anybody has managed to get it work correctly on a CRT using the MIST (the MiSTER seems to work well).

https://drive.google.com/file/d/1b1BOXyalkyoc80vPWyyEpzXs-97Rf-Ff/view?usp=sharing

**Comment by jotego** [comment]
Please try the file jtdd2_20200111b.rbf in Google Drive. I have widen out the sync pulses. Let's see if that helps.

**Comment by manast** [comment]
Ok, I was referring to DD1, and since there is no .sh to convert the rom I could not test DD2, however I tried to load the core and the OSD menu is being displayed correctly, so I think the widening of the sync pulses did it, could you release DD1 with the same fix?

**Comment by jotego** [comment]
Yes, that's a very good sign. I have uploaded the buildrom.sh which generates the ROM file for both games. I am compiling the DD1 version with wide pulses now and it will in Google Drive in 15 minutes.

**Comment by manast** [comment]
Amazing, thanks!

**Comment by jotego** [comment]
The new DD1 core is called jtdd_20200111.rbf

**Comment by manast** [comment]
Works almost perfect, one small "wave" kind of glitch on the top though:
![image](https://user-images.githubusercontent.com/95200/72248412-65d6ed80-35f7-11ea-9439-2b56b2ee4867.png)

**Comment by jotego** [comment]
Hi Manuel,

I have got one more report similar to yours about CPS. I will be checking once more the MiST video signal path to try and figure out what's causing the issue.

Stay tuned ;-)

**Comment by manast** [comment]
yeah, I was actually counting the days for you to finalize CPS so that you could find time to look into this :)

**Comment by jotego** [comment]
I close it now. Double Dragon public version -to be publish this month, I hope- will incorporate the fix we have already tried on CPS0 cores.
