### ISSUE TITLE
Black Tiger froze after finishing the game at the STOP / WARNING screen

### ISSUE THREAD

**Issue by Chocobobobo** [jotego/jt_gng#42]
As I was checking your fix for #41 using the 0226 rbf you uploaded, I could confirm the game didn't freeze after beating a boss. (I will test it more).
Everything seemed fine; until I finished the game.
After the credits; the game froze on the "Stop don't use this game if you are outside blablabla WARNING" screen. I couldn't do anything, the game softlocked / froze. I will try to repro it but entered it here to keep track of it. Thanks for your help fixing those and working on CPS at the same time, and maybe on a NES cart reader; who knows :)

**Comment by jotego** [comment]
Let me close it here and we track the issue through thread #41.
