### ISSUE TITLE
Garbled sprites 

### ISSUE THREAD

**Issue by the1ross** [jotego/jt_gng#45]
The older Jotegi cores work fine but new ones like Tiger Road, F1 and Bionic Commando don't work properly for me. Many of the sprites are either garbled or don't appear at all. 

I've not had this problem with any other cores including all the arcade ones. I was hoping that after an update or two, things would fix themselves, but they haven't. Any advice would be appreciated. 
![2020-03-07 11 33 29](https://user-images.githubusercontent.com/44575172/76135134-92433f00-6067-11ea-8c26-28205690c55b.jpg)

**Comment by the1ross** [comment]
In this one enemy sprites among others don't appear and bionic command disappears. 

![2020-03-07 11 35 19](https://user-images.githubusercontent.com/44575172/76135181-e8b07d80-6067-11ea-90e5-f9fd17ba9adf.jpg)

**Comment by the1ross** [comment]
F1

![2020-03-07 11 40 05](https://user-images.githubusercontent.com/44575172/76135239-68d6e300-6068-11ea-8233-fa7be98e3cce.jpg)

**Comment by the1ross** [comment]
Black Tiger is the only newer core of you're that works perfectly. Gng, 1942, 1943, gunsmoke etc all work fine also.

**Comment by jotego** [comment]
I close this thread. Let's track this problem [here](https://github.com/jotego/jtbin/issues/4).
