### ISSUE TITLE
Black Tiger top line

### ISSUE THREAD

**Issue by jotego** [jotego/jt_gng#46]
Sometimes a horizontal line will appear at the top of the screen.
![imagen](https://user-images.githubusercontent.com/1863036/76254566-f96e1880-624c-11ea-88a2-d20a10dd5353.png)

**Comment by Chocobobobo** [comment]
Still occuring with the current latest build, 0319.

**Comment by jotego** [comment]
This apparently was caused by changes to the "layout" flip flop by the CPU outside blanking. The layout value is now latched at the beginning of each horizontal line. I don't know whether the original implementation was like that, or whether the FF was gated by blanking signals.

Fixed in https://github.com/jotego/jtbin/commit/e2f3272c5fcccdd0e116ff2a58635fea39bf1257
