### ISSUE TITLE
insert coin sound in Section Z

### ISSUE THREAD

**Issue by jotego** [jotego/jt_gng#48]
Original recording [here](https://www.youtube.com/watch?v=cIC2mNNryZg&list=PLtrmDPZ4GNbkBO4P_rlSE02KDTTwsJqQf&index=7&t=22s).

**Comment by paulb-nl** [comment]
That is a Mame recording though.

**Comment by paulb-nl** [comment]
Here is a video of a pcb although recorded with a camera.
https://youtu.be/je_h3TBx5Ps?t=158

**Comment by jotego** [comment]
Fixed in JT49's commit https://github.com/jotego/jt49/commit/57619f8b06487454d8a7e345590fcce4c14e6fc4
I'll update the cores in my repositories that use JT49/JT12 with this version soon.
