### ISSUE TITLE
Gun.Smoke game sprites not displaying properly as of 8/25/2020

### ISSUE THREAD

**Issue by thepulserifle** [jotego/jt_gng#55]
![E9BB408F-3CEB-481A-A714-B10FF1E6EBC3](https://user-images.githubusercontent.com/60025144/91297138-9fa5d000-e752-11ea-9d67-6f7cfa162d26.jpeg)

Steps to reproduce:

Boot up on latest. See screenshot for example.

**Comment by jotego** [comment]
I think they said in Discord that this had to do with old config files in MiSTer. I haven't been able to reproduce the problem so I'm assume things are ok now.
