### ISSUE TITLE
Vulgus and 1942 some pixellines are missing

### ISSUE THREAD

**Issue by cavemanxzx** [jotego/jt_gng#56]
Vulgus and 1942 some pixellines are missing. In the Pictures on the Top. It's the same on my HDMI screen.

![IMG_20200902_171714125](https://user-images.githubusercontent.com/60032126/92003091-e55d2c80-ed40-11ea-8823-df7aeeabcbf1.jpg)
![IMG_20200902_171651118](https://user-images.githubusercontent.com/60032126/92003100-e8581d00-ed40-11ea-9868-432234bb2e89.jpg)

**Comment by jotego** [comment]
It's fixed now. Files are available in jtbin https://github.com/jotego/jtbin/commit/1290b19e905b56039331b2dd09a7193ba6ecf3b7
