### ISSUE TITLE
1942 - CAPCOM logo/title screen animation

### ISSUE THREAD

**Issue by Maestrobob** [jotego/jt_gng#64]
The title screen animations of the CAPCOM logo (in both variants) behave incorrectly.

reference video (right side is correct behavior) - https://youtu.be/cKloM2DgHQE

This used to work perfectly in much older builds of the core.

**Comment by jotego** [comment]
I broke it in one update, and I haven't got back to it yet. Thanks for adding it here so I don't forget about it.

**Comment by jotego** [comment]
Fixed in c89b69ab

**Comment by jotego** [comment]
The fix causes some sprites not to show

**Comment by jotego** [comment]
Fixed
