### ISSUE TITLE
Speed Rumbler - Game freezes when entering final boss

### ISSUE THREAD

**Issue by skutis** [jotego/jt_gng#67]
Speed rumbler freezes when entering final boss.
- This was without car, perhaps not important.
- There was some garbled graphics in the upper left corner just before it froze.
- The music kept playing although everything else was frozen.

![IMG_4470](https://user-images.githubusercontent.com/80739822/117584867-9eb1a480-b10f-11eb-8d6c-05ff837446e7.JPEG)

https://user-images.githubusercontent.com/80739822/117584869-9fe2d180-b10f-11eb-987d-e1c2d8f9ce8d.MP4

**Comment by jotego** [comment]
I think this is due to the CPU address changing while RnW signal is low. The SDRAM controller doesn't like that. I will try making some changes...

**Comment by jotego** [comment]
Not only the CPU address, but the data may also change too in that CPU module:

![imagen](https://user-images.githubusercontent.com/1863036/152655190-e2f3f417-6e75-4ece-a4f7-7a1731503eab.png)

The image comes from the unrelated proto1 project but shows how data for a 16-bit write operation changes while RnW and address is stable. This doesn't suite the SDRAM controller at all

**Comment by jotego** [comment]
I think this is fixed in issue 60f94df. Although, I haven't tested it playing the full game. I will update the binaries in a few minutes.
