### ISSUE TITLE
Strange noise in the second stage

### ISSUE THREAD

**Issue by manast** [jotego/jt_gng#7]
in the second stage (ice castle) there is some strange background noise. Its almost like a one of the platforms makes a noise that fills too much, not sure.

**Comment by jotego** [comment]
If you play the game on MiSTer through HDMI you may be getting a resampling effect due to the difference in audio sampling rates of the original hardware compared to HDMI. Try using directly the analog audio output.

**Comment by manast** [comment]
This is on a MiST, using standard analog output. I am using the latest image from 9th Februari, latest MiST firmware as well. The noise is quite loud, should be easy to reproduce it happens every time on the ice stage.

**Comment by jotego** [comment]
Could you provide a video of this?

**Comment by manast** [comment]
Ok, it took me a while but here is the video anyway: https://s3.eu-central-1.amazonaws.com/castmill-medias/IMG_6538.MOV
What do you think? I do not remember this strange sound on the original arcade, but it was long time ago...
