### ISSUE TITLE
Street fighter black lines

### ISSUE THREAD

**Issue by paulb-nl** [jotego/jt_gng#70]
There is a 1px black line at the top and a 2px black column on the right.

![20210522_120218-screen](https://user-images.githubusercontent.com/2227984/119241508-1bed0880-bb57-11eb-8fdb-3a93c8bcc6bb.png)

**Comment by jotego** [comment]
Confirmed in version 879d977a
There seems to be missing pixels but the visible area size is correct. We'll check more.

**Comment by jotego** [comment]
The top black line was due to the SDRAM not serving GFX data during the vertical blank

**Comment by jotego** [comment]
The right columns were hidden by black OBJ layer pixels, which should not have been there. Fixed in 518600b
