### ISSUE TITLE
F-1 Dream - Aspect Ratio Incorrect on HDMI

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jt_gng#72]
HDMI and Analog aspect ratios are different. 

The circles of the countdown lights when starting a race and character portrait squares during the intro, indicate that HDMI is stretching further than it should.  Looks like it is assuming 4:3 for HDMI but the game is a slightly different aspect.

**Comment by jotego** [comment]
This game has the same resolution as GnG. But GnG is compiled at 5:4 and this one is at 4:3. And you don't like any of them. That's why I say that there's no good solution.
Please use a custom setting that fits your screen.
Sorry, but I cannot do anything more.
