### ISSUE TITLE
Ghosts N Goblins - Aspect Ratio Incorrect on HDMI

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jt_gng#73]
HDMI aspect ratio is stretched beyond what is show on analog output.

In this case it is a minor difference, but the game is definitely stretched on HDMI.

**Comment by jotego** [comment]
People have different opinions about this. I have already changed it in the past (it used to be 4:3), but there is no value that pleases everyone. The core supports a custom aspect ratio in the .ini file. I think it's better to customize it there.
Sorry, but I don't think there is a universal solution for this.
