### ISSUE TITLE
F-1 Dream - Aspect Ratio Incorrect on HDMI (with examples)

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jt_gng#74]
HDMI aspect ratio is incorrect in this core.  You previously commented about how this was somehow a matter of "preference", but I would refer you to the artwork in the game itself to determine what is correct.  See the two example screenshots for examples that can be used to dial in the correct aspect ratio here.  I am adamant that the correct aspect should be the default, and not be the responsibility of the end user to make custom aspect ratios in their mister.ini to achieve.  This is how other cores do it, and I hope that this one can be brought up to speed and made correct as well.

-Example 1-
The circles of the countdown lights when starting a race, and the 'position indicator' box in the bottom-center of the screen should give you a good idea of what the correct aspect is.  The lights should appear perfectly round, as traffic lights always are, and the 'position indicator' in bottom-center should be square. See below screenshot for an example of how these currently look on HDMI:
![untitled](https://user-images.githubusercontent.com/40709481/127256509-9238cbd3-26f7-4ffd-86e9-0cb414fc7c02.png)

-Example 2-
Character portrait squares during the intro also indicate that HDMI is stretching further than it should.  While these aren't perfectly square on analog either, they are very close to it, whereas HDMI has them very clearly stretched horizontally:
![untitled2](https://user-images.githubusercontent.com/40709481/127256513-e86c731c-e33b-4e20-93ac-8e50ab3e819e.png)

**Comment by jotego** [comment]
Using
```
[f1dream]
custom_aspect_ratio_1=48:41
```
in the mister.ini renders an aspect ratio that looks rather square for the portraits. The numbers are based on how the MiST analogue output look. The umbrellas look better too.

I'll change the hard-coded values for the next release. In the meantime, you may use the mister.ini solution.

Thanks for the detailed report.
