### ISSUE TITLE
Trojan - Elevators play double sound effect

### ISSUE THREAD

**Issue by Aquas77** [jotego/jt_gng#77]
I thought this was odd and something I hadn't heard before. The elevators seem to double up their sound as you ride down them. 

As heard in this clip using Trojan (US set 2):
https://clips.twitch.tv/LittleTrustworthyStingrayCorgiDerp

Still on 32mb ram

**Comment by jotego** [comment]
Sorry Aquas, I'm listening to this and cannot find anything odd about it. MAME, for a reference, sounds the same to me.
