### ISSUE TITLE
Street Fighter - DIP Switches

### ISSUE THREAD

**Issue by Kopert** [jotego/jt_gng#78]
I have two issues to report with the DIP Switches on the Street Fighter core.

1. "Game Continuation" and "Buy-In Feature" switch between "None" and 5 empty options with no string. Furthermore, when it comes to "Game Continuation" the operator's manual states that, to have "5h Stage Maximum" (continue available up to and including the fifth, final stage), all 3 values should be off (zero). However, if you get to service mode and navigate through all the "Game Continuation" dip switch options, the three numbers it manipulates on screen NEVER reach zero all at the same time; therefore, it is not possible to get "Game Continuation" all the way to "5th Stage Maximum". I managed to hexedit the .dip file to get those values all to zero, which allowed me to use continues on the 5th stage.

2. The default values for the DIP Switches are wrong. According to the Operator's Manual, the default values ("Manufacturer's recommended settings") are all switches to Off, which gives "5th Stage Maximum" and "Normal Difficulty" by default. This is not the default the core operates with if you don't change any DIP Switches around.

Reference: pages 1-5 and 1-6 of the [Operator's Manual](https://www.arcade-museum.com/manuals-videogames/S/Street%20Fighter%20Operators%20Manual%20With%20Illustrated%20Parts%20Lists.pdf).

**Comment by atrac17** [comment]
Fixed in jtbin (https://github.com/jotego/jtbin/commit/4acf55ff103fd264d57d1487e41f899e1b116988)

**Comment by jotego** [comment]
Thank you. I have copied your modified MRA file to this repository too. I'm closing the issue.
