### ISSUE TITLE
Street Fighter - Freezes on some 128 MB SDRAM modules

### ISSUE THREAD

**Issue by coolbho3k** [jotego/jt_gng#82]
Street Fighter freezes on this screen on just one of my 128 MB SDRAM modules. Just how much text appears before it freezes can vary - sometimes it freezes on the black screen, sometimes it prints more text.

![Screen Shot 2022-04-14 at 12 24 16 PM](https://user-images.githubusercontent.com/303270/163461756-8b2c9a45-7612-4266-8796-264f17401fbc.png)

I have three 128 MB XS 2.9 modules.

- One from misterfpga.co.uk has never booted the game fully (2x AS4C32M16SB-7TCN).
- One from misterfpga.co.uk can boot regularly (2x AS4C32M16SB-7TCN) I did just get one crash but the game starts successfully the next time.
- One from misteraddons.com hasn't ever crashed (2x AS4C32M16SB-7TIN).

I also see red lines on in the Japanese flag on the country select screen. Not sure which modules it appears on and not sure if it's related.

**All 3 modules pass 150 MHz on memtest and jtsdram 48 MHz and 96 MHz tests for at least 20 mins and seem to work for many other cores I've tested** so the DRAM is probably fine. I'm attributing this to some timing quirks between my DE10-Nano unit, the particular RAM module, and the core.

**Comment by jotego** [comment]
Thank you for the detailed feedback. Some MRA files for this game refer to MCU-based versions that don't work correctly. But, if you're referring to the US set 1, I am sorry I cannot do anything about this. The SDRAM solution on MiSTerFPGA is far from perfect from an electrical standpoint. Older, hand-soldered modules are known to be much less reliable than the ones produced in the last year or so when practically all sellers moved to factory manufactured modules.
